spring:
  application:
    name: spring-lab-01

server:
  port: 8080

app:
  owner: Sagyndyk Abzal
  group: IT-2410IS
  repeat-count: 3

  mail:
    from: no-reply@iitu.kz
    retry-count: 3
    timeout: 5s
    enabled: true

  cache:
    ttl: 10m
    max-entries: 1000

logging:
  level:
    web: INFO
    kz.iitu: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,env,configprops,conditions